modLoader = "javafml"
loaderVersion = "[2.0,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mixins]]
config = "trymod.mixins.json"

[[mods]]
modId = "trymod"
version = "${version}"
displayName = "try mod"
authors = "Me!"
description = '''
try
'''
#logoFile = ""

[[dependencies.trymod]]
modId = "neoforge"
type = "required"
versionRange = "[20.4.114-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trymod]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trymod]]
modId = "architectury"
type = "required"
versionRange = "[11.0.11,)"
ordering = "AFTER"
side = "BOTH"
